package:
    name:           hipanel-module-dashboard
    namespace:      hipanel\modules\dashboard
    label:          DashboardModule
    title:          Dashboard Plugin for HiPanel
    type:           yii2-extension
    keywords:       dashboard, hipanel, plugin
    year:           2014

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
